### PR TITLE
change select2 widgets in order to work within dynamic matrix fields

### PR DESCRIPTION
**Pull request by masciugo**
to do that I needed to change the way the 2 widgets are activated which is always by property. There is probably a better solution but this is the best I could do in few hours

Here is a plunker to try my package version
https://plnkr.co/edit/0F3tGe?p=preview

### CODE REVIEW

**Comment by andrewtelnov** [comment]
@masciugo You do not need to do anything. It is already working. All you need is to add the following code, before creating the survey:
`Survey.CustomWidgetCollection.Instance.setActivatedBy("select2", "type");`
Here is [the example](https://plnkr.co/edit/Etr32f8qkR7rb4gmVIpF?p=preview)

Thank you,
Andrew

**Comment by masciugo** [comment]
thank you Andrew

maybe my description was unclear. What I'd like to show with my plunker was the ability to have all 6 combinations working:

- dropdown
- dropdown with select2
- tagbox 
- matrix with dropdown
- matrix with dropdown with select2
- matrix with tagbox

Ok with your suggestion I can have select2 enabled on all dropdown, matrix ones included. But I cannot do the same with tagbox. `cellType` does not seem to understand tagbox as type... and property is not considered [here](https://github.com/surveyjs/widgets/blob/master/src/select2-tagbox.js#L13-L15). Am I still missing something?

**Comment by andrewtelnov** [comment]
@masciugo I have just add [a comment](https://github.com/surveyjs/surveyjs/issues/869#issuecomment-358305696).

Thank you,
Andrew

**Comment by masciugo** [comment]
Andrew, I revisited [your example](https://plnkr.co/edit/Etr32f8qkR7rb4gmVIpF?p=preview) but it does not seem to work anymore. In the example select2 should be activated on any dropdown input type but it's not even outside the matrix. Does it have anything to do with the new release? thanks

**Comment by andrewtelnov** [comment]
@masciugo Could you please try our latest release and the code that shown in [this issue](https://github.com/surveyjs/surveyjs/issues/876)

Thank you,
Andrew

**Comment by masciugo** [comment]
it seems ok! https://plnkr.co/edit/F8UA6vg7uDmkunjFq67i?p=preview

thank you

**Pull request closed without merging**
