### PR TITLE
Compile package with babel

### PR DESCRIPTION
**Pull request by juliankrispel**
This package isn't compiled with babel although it uses es6 and beyond, meaning it breaks in IE10. This pr fixes that...

- [x] compile source code with babel
- [x] upgrade webpack

### CODE REVIEW

**Comment by juliankrispel** [comment]
But there is es6 syntax in the source code! Just look for „const“ in any
given file

**Comment by dmitrykurmanov** [comment]
@juliankrispel we've fixed it via the https://github.com/surveyjs/widgets/commit/d1ee539d975bd893a8c8e657cc904630f6cf5f01

**Comment by juliankrispel** [comment]
@dmitrykurmanov when will this be released?

**Comment by dmitrykurmanov** [comment]
@juliankrispel probably today

**Pull request closed without merging**
